### ISSUE TITLE
PortBridge and dotnet core compatibility

### ISSUE THREAD

**Issue by nonoxp** [Azure/azure-relay#53]
# Description
I'm not sure if this is about the client library or not, I'm using Microsoft.Azure.Relay 2.0.1 on top of .Net Core 3.1 (Windows 10).
Did anyone try to convert it for .net core and have some tips to share?
I'm trying to convert this project, it builds fine but at runtime the following problem occurs.

On the server side, in the BufferPump class of PortBridge library, the following method fails when bufferRead.BeginInvoke is called (rawInputPump).

```
public override IAsyncResult BeginRunPump(AsyncCallback callback, object state)
{
    if (IsRunning)
    {
        throw new InvalidOperationException("Already running");
    }
    IsRunning = true;
    Caller = new PumpAsyncResult(callback, state);
    bufferRead.BeginInvoke(inputBuffer, 0, inputBuffer.Length, DoneReading, null);
    return Caller;
}
```
Exception thrown is:
```
System.PlatformNotSupportedException "Operation is not supported on this platform."
   at PortBridge.BufferRead.BeginInvoke(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object object)
   at PortBridge.BufferPump.BeginRunPump(AsyncCallback callback, Object state) in BufferPump.cs:line 33
   at PortBridge.TcpClientConnectionForwarder.EnsureConnection() in TcpClientConnectionForwarder.cs:line 203
   at PortBridge.TcpClientConnectionForwarder.ClientAccepted(IAsyncResult asyncResult) in TcpClientConnectionForwarder.cs:line 150
```

Other samples on run OK on top of .net core, but PortBridge is the one that can't. It's also the only one that use the stream Read method like this.
Does this mean the dataChannel (HybridConnectionStream)  created in TcpClientConnectionForwader cannot be used anymore in dotnet core?

I quickly compared with a watcher the dataChannel stream object in dotnet core and .NET 4.6.1, but there was no obvious difference. Both are non-seekable, and both throw an exception on Length and Position properties getter, there has to be something else.

Same test for the inputPump and outputPump, they end up causing a NotSupportedException when the bufferRead is called.

**Comment by nonoxp** [comment]
Answering to myself and others that would attempt the adventure.
Nevermind, I found a way to perform what I want to do with the implementation pattern in this sample.
https://github.com/Azure/azure-relay-bridge

The Task/ContinueWith pattern is more elegant and maintenable than the IAsyncResult handling.
